alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
global:
  scrape_interval: 15s
rule_files:
- alerts.yml
scrape_configs:
- job_name: causal-discovery
  metrics_path: /metrics
  scrape_interval: 10s
  static_configs:
  - targets:
    - causal-discovery:8080
